# Generated by Django 2.2 on 2019-04-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer_right',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_wrong',
            field=models.IntegerField(default='0'),
        ),
    ]
